# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-XTii6MRshHOlGev5t8mSmjMtrtf07YN
"""

##Importing the libraries
from flask import Flask, render_template, request
import numpy as np
import pandas as pd
import pickle

app = Flask(__name__)
pickle_in = open("classifier.pkl","rb")
classifier = pickle.load(pickle_in)
@app.route("/", methods=["GET"])
def home():
  return render_template("index.html")
@app.route("/predict", methods=["POST"])
def predict():
  if request.method == 'POST':
    result = request.form
    new_result = list(result.values())
    for i in range(len(new_result)):
      new_result[i] = float(new_result[i])
    prediction = classifier.predict([new_result])
    if prediction==1:
      return "Unauthenticated Note (Fake Note)"
    else :
      return "Authenticated Note (Real Note)"
if __name__ == '__main__':
    app.run(debug=True)
