# -*- coding: utf-8 -*-
"""banknote.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PkVtxrLrYrEUg3eGtNvL2sH-bZsySuEH

##Importing the Libraries
"""

import numpy as np
import pandas as pd

"""##Importing the dataset

"""

dataset = pd.read_csv("BankNote_Authentication.csv")
dataset.head()

dataset.isnull().sum()

"""##Independent and Dependent """

X  = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

X.shape

"""##Split the dataset

"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

"""##Training the model"""

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 37, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

"""##Predicting the Test set Results"""

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

"""##Making the Confusion metrics

"""

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

"""##Create a Pickle file"""

import pickle
pickle_out = open("classifier.pkl","wb")
pickle.dump(classifier,pickle_out)
pickle_out.close()